# Generated by Django 4.0.4 on 2022-04-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='age',
            field=models.IntegerField(),
        ),
    ]
