# Generated by Django 4.0.4 on 2022-08-13 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_form', '0002_alter_survey_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='email',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='role',
        ),
        migrations.AddField(
            model_name='survey',
            name='birthdate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='survey',
            name='city',
            field=models.CharField(default='Tunja', max_length=200),
        ),
        migrations.AddField(
            model_name='survey',
            name='extra_act',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='survey',
            name='height',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='survey',
            name='last_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='survey',
            name='lives_with',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='survey',
            name='phisical_act',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='survey',
            name='sleep_hours',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='survey',
            name='subject',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='survey',
            name='subject_grade',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='survey',
            name='weight',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='survey',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='survey',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
